name: Daily Market Report

on:
  schedule:
    - cron: '0 0 * * *' # 每天零点执行
  workflow_dispatch: # 手动触发

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update_market_data.py
      run: |
        echo "Running update_market_data.py..."
        python update_market_data.py

    - name: Check if market_data.json is updated
      run: |
        if [ -f market_data.json ]; then
          echo "market_data.json exists and has been updated."
        else
          echo "market_data.json does not exist or was not updated."
        fi

    - name: Commit and push updated market_data.json
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add market_data.json
        git commit -m "Update market_data.json"
        git push
